// Generated by CoffeeScript 1.6.3
(function() {
  var TD, points, roadArr;

  points = 0;

  roadArr = [];

  TD = function(opts) {
    this.mapWrap = opts.mapWrap;
    this.gunWrap = opts.gunWrap;
    this.propertyWrap = opts.propertyWrap;
    return this.init();
  };

  TD.prototype = {
    init: function() {
      var curMaps, curPoint, k, m, map, n, newN, newR, r, that, v, _i, _j, _len, _len1;
      that = this;
      curPoint = MAPS[points];
      curMaps = curPoint.map;
      n = 0;
      for (n = _i = 0, _len = curMaps.length; _i < _len; n = ++_i) {
        map = curMaps[n];
        for (r = _j = 0, _len1 = curMaps.length; _j < _len1; r = ++_j) {
          m = curMaps[r];
          if (curMaps[n][r] < 1) {
            curMaps[n][r] = 0;
          } else {
            newR = r * 20;
            newN = n * 20;
            roadArr.push([newR, newN, that.uploadMap(newR, newN, curMaps[n][r])]);
          }
        }
      }
      for (k in GUN) {
        v = GUN[k];
        that.creatItem("<strong>" + k + "</strong>\n<span class=\"price\">价格：" + v.price + "</span>\n<span class=\"range\">攻击范围：" + v.range + "</span>\n<span class=\"interval\">攻击速度：" + v.interval + "</span>\n<span class=\"attack\">攻击力：" + v.attack + "</span>", k, that.gunWrap);
      }
      that.creatItem("<span class=\"life\">血量：" + curPoint.life + "</span>\n<span class=\"money\">金币：" + curPoint.money + "</span>", "pt", that.propertyWrap);
    },
    uploadMap: function(left, top, n, wrap, cls) {
      var m, mapWrap;
      m = document.createElement('div');
      mapWrap = wrap || this.mapWrap;
      m.className = cls || 'road';
      m.style.cssText = "position:absolute;\nleft:" + left + "px;\ntop:" + top + "px;";
      if (n === 2) {
        m.className = 'end';
      }
      mapWrap.appendChild(m);
      return m;
    },
    creatItem: function(ht, key, obj) {
      var m, that;
      that = this;
      m = document.createElement('div');
      m.className = "gun " + key;
      m.innerHTML = ht;
      obj.appendChild(m);
    }
  };

  new TD({
    mapWrap: document.getElementById('map'),
    gunWrap: document.getElementById('fort'),
    propertyWrap: document.getElementById('property')
  });

}).call(this);
